### ISSUE TITLE
Limit returned guesses

### ISSUE THREAD

**Issue by BenBE** [WestpointLtd/tls_prober#11]
It would be nice to have some option like with the unix head command to limit the display of guesses t the top N entries.

E.g. have:
    ./probe.py -5 example.org
return the top 5 most likely implementations for example.org

If missing or 0 return full list as usual:
    ./probe.py example.org
    ./probe.py -0 example.org
Both return the full list of guesses in decending order of likeliness.

**Comment by richmoore** [comment]
Agreed. I'll implement something like this.

**Comment by richmoore** [comment]
Resolved
