### ISSUE TITLE
Missing Socket Timeout Exception Handling

### ISSUE THREAD

**Issue by onursoyer** [WestpointLtd/tls_prober#37]
Hello,

I've been encountering socket timeout exception. 

[How to Produce Error]

```
$ ./prober.py www.google.com
Traceback (most recent call last):
  File "./prober.py", line 420, in <module>
    main()
  File "./prober.py", line 389, in main
    results = probe(args[0], opts.port, opts.starttls, opts.probe)
  File "./prober.py", line 329, in probe
    result = probe.probe(ipaddress, port, starttls)
  File "/home/onur/tp/tls_prober/probes.py", line 124, in probe
    sock = self.connect(ipaddress, port, starttls)
  File "/home/onur/tp/tls_prober/probes.py", line 49, in connect
    s.connect((ipaddress, port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.timeout: timed out
```

[Posibble Fix]
I believe problem occurs in [here](https://github.com/WestpointLtd/tls_prober/blob/master/probes.py#L124). Looks like that line is put outside of try block by accident.

I would like to send a pull request for this patch if it is okay.

Thank you.

**Comment by tomato42** [comment]
no, it's correct

if this timeout is raised, it means that the server essentially rejected the connection, but not on TLS level, but rather on TCP level. prober can't do anything with this

so it should not be placed in the existing try block, if anything, this exception should be caught higher in stack and print an error like "Can't connect to server" or something
